### ISSUE TITLE
Erro de compilação

### ISSUE THREAD

**Issue by DanteCampos** [braully/graph-problems-tool#25]
Não é possível compilar por algum erro de reconhecimento da função List.of()

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /home/hebert/graph-problems-tool/src/test/java/com/github/braully/graph/BFSUpdateTest.java:[44,30] cannot find symbol
  symbol:   method of(int,int,int,int)
  location: interface java.util.List
[ERROR] /home/hebert/graph-problems-tool/src/test/java/com/github/braully/graph/BFSUpdateTest.java:[45,29] cannot find symbol
  symbol:   method of(int,int,int,int)
  location: interface java.util.List
[ERROR] /home/hebert/graph-problems-tool/src/test/java/com/github/braully/graph/BFSUpdateTest.java:[46,29] cannot find symbol
  symbol:   method of(int,int,int,int)
  location: interface java.util.List
[ERROR] /home/hebert/graph-problems-tool/src/test/java/com/github/braully/graph/BFSUpdateTest.java:[47,29] cannot find symbol
  symbol:   method of(int,int,int,int)
  location: interface java.util.List
[ERROR] /home/hebert/graph-problems-tool/src/test/java/com/github/braully/graph/BFSUpdateTest.java:[48,29] cannot find symbol
  symbol:   method of(int,int,int,int)
  location: interface java.util.List
[ERROR] /home/hebert/graph-problems-tool/src/test/java/com/github/braully/graph/BFSUpdateTest.java:[49,29] cannot find symbol
  symbol:   method of(int,int,int,int)
  location: interface java.util.List
[ERROR] /home/hebert/graph-problems-tool/src/test/java/com/github/braully/graph/BFSUpdateTest.java:[50,29] cannot find symbol
  symbol:   method of(int,int,int,int)
  location: interface java.util.List
[ERROR] /home/hebert/graph-problems-tool/src/test/java/com/github/braully/graph/BFSUpdateTest.java:[51,29] cannot find symbol
  symbol:   method of(int,int,int,int)
  location: interface java.util.List
[ERROR] /home/hebert/graph-problems-tool/src/test/java/com/github/braully/graph/BFSUpdateTest.java:[52,29] cannot find symbol
  symbol:   method of(int,int,int,int)
  location: interface java.util.List
[ERROR] /home/hebert/graph-problems-tool/src/test/java/com/github/braully/graph/BFSUpdateTest.java:[53,29] cannot find symbol
  symbol:   method of(int,int,int,int)
  location: interface java.util.List

**Comment by braully** [comment]
Essa função só existe no Java >= 11. Tente atualizar o seu jdk

**Comment by DanteCampos** [comment]
Atualizei e continua sem conseguir compilar:

Exception in thread "main" com.google.common.util.concurrent.ExecutionError: java.lang.NoClassDefFoundError: Could not initialize class com.google.inject.internal.cglib.core.$ReflectUtils
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203)
        at com.google.common.cache.LocalCache.get(LocalCache.java:3951)
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3955)
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4870)
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4876)
        at com.google.inject.internal.FailableCache.get(FailableCache.java:48)
        at com.google.inject.internal.ConstructorInjectorStore.get(ConstructorInjectorStore.java:50)
        at com.google.inject.internal.ConstructorBindingImpl.initialize(ConstructorBindingImpl.java:137)
        at com.google.inject.internal.InjectorImpl.initializeBinding(InjectorImpl.java:533)
        at com.google.inject.internal.AbstractBindingProcessor$Processor$1.run(AbstractBindingProcessor.java:160)
        at com.google.inject.internal.ProcessedBindingData.initializeBindings(ProcessedBindingData.java:44)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:123)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:107)
        at com.google.inject.Guice.createInjector(Guice.java:99)
        at com.google.inject.Guice.createInjector(Guice.java:73)
        at com.google.inject.Guice.createInjector(Guice.java:62)
        at org.codehaus.plexus.DefaultPlexusContainer.addPlexusInjector(DefaultPlexusContainer.java:481)
        at org.codehaus.plexus.DefaultPlexusContainer.<init>(DefaultPlexusContainer.java:206)
        at org.apache.maven.cli.MavenCli.container(MavenCli.java:545)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:281)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.google.inject.internal.cglib.core.$ReflectUtils
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.getProtectionDomain(FastClass.java:73)
        at com.google.inject.internal.cglib.core.$AbstractClassGenerator.create(AbstractClassGenerator.java:206)
        at com.google.inject.internal.cglib.reflect.$FastClass$Generator.create(FastClass.java:65)
        at com.google.inject.internal.BytecodeGen.newFastClass(BytecodeGen.java:204)
        at com.google.inject.internal.DefaultConstructionProxyFactory.create(DefaultConstructionProxyFactory.java:55)
        at com.google.inject.internal.ProxyFactory.create(ProxyFactory.java:159)
        at com.google.inject.internal.ConstructorInjectorStore.createConstructor(ConstructorInjectorStore.java:90)
        at com.google.inject.internal.ConstructorInjectorStore.access$000(ConstructorInjectorStore.java:29)
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:37)
        at com.google.inject.internal.ConstructorInjectorStore$1.create(ConstructorInjectorStore.java:33)
        at com.google.inject.internal.FailableCache$1.load(FailableCache.java:37)
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3540)
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2321)
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2284)
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2199)
        ... 28 more

**Comment by braully** [comment]
Corrigido no ultimo merge request: https://github.com/braully/graph-problems-tool/actions/runs/2993891414
